#!/usr/bin/python

"""Amulet tests on a basic openstack-dashboard deployment on utopic-juno."""

from basic_deployment import OpenstackDashboardBasicDeployment

if __name__ == '__main__':
    deployment = OpenstackDashboardBasicDeployment(series='utopic')
    deployment.run_tests()
