#!/usr/bin/python

"""Amulet tests on a basic openstack-dashboard deployment on trusty-liberty."""

from basic_deployment import OpenstackDashboardBasicDeployment

if __name__ == '__main__':
    deployment = OpenstackDashboardBasicDeployment(series='trusty',
                                                   openstack='cloud:trusty-liberty',
                                                   source='cloud:trusty-updates/liberty')
    deployment.run_tests()
