#!/usr/bin/python

"""Amulet tests on a basic openstack-dashboard deployment on wily-liberty."""

from basic_deployment import OpenstackDashboardBasicDeployment

if __name__ == '__main__':
    deployment = OpenstackDashboardBasicDeployment(series='wily')
    deployment.run_tests()
