#!/usr/bin/python

"""Amulet tests on a basic openstack-dashboard deployment on xenial-mitaka."""

from basic_deployment import OpenstackDashboardBasicDeployment

if __name__ == '__main__':
    deployment = OpenstackDashboardBasicDeployment(series='xenial')
    deployment.run_tests()
